### ISSUE TITLE
Not working with `dotspacemacs-themes`

### ISSUE THREAD

**Issue by elandx** [thblt/eziam-theme-emacs#16]
Hi, thanks for the great theme! 
I use Spacemacs. Usual way to set colour theme here is to define it with the variable `dotspacemacs-themes`. E.g. i can write `tao-yang` and all is ok. But if i try the same thing this `eziam-light`, Spacemacs fired `error: (error Unable to find theme file for ‘eziam-light’)` and trying to install `eziam-light-theme`.
Of course, this is Spacemacs-specific problem, but with other themes having light and dark versions (tao-theme, spacemacs-theme, solarized-theme) it works fine.
Thanks in advance

**Comment by thblt** [comment]
Hi,

I have zero experience with Spacemacs.  Could you please explain how you've installed Eziam?  Does it use the standard package manager?

**Comment by elandx** [comment]
Thanks for the answer. 
I have installed Eziam from ELPA, just like other packages. I think that Spacemacs uses the paradox package as its package manager. Now i have `eziam-theme-20170915.540` in my `.emacs.d/elpa` directory if it matters. For some reason that I do not understand Spacemacs' mechanism of colour theme initialization during start can use light and dark variants of other themes but Eziam. After the start i can choose `eziam-light` and it works just fine.

**Comment by thblt** [comment]
I've asked the spacemacs Gitter chat, and got this answer:

> @duianto
> 21:54
> @thblt It seems to be working as expected for me on the develop branch. I added eziam-theme to the .spacemacs dotspacemacs-additional-packages list, restarted and let the theme download. Now I'm able to switch to the eziam-dark and eziam-light theme from the SPC T s HELM Themes buffer.
It's working fine on the master branch as well.

Could you try what they describe and see if it works?

**Comment by elandx** [comment]
Thanks again.
It works for me too if i switch theme as described in your answer. My
problem is: i can't set eziam-light at the Spacemacs start from my init
file. It keep trying to install `eziam-light-theme` and failing for obvious
reason. Once again, i have Eziam theme installed, but Spacemacs can't use
it properly on the start.

**Comment by thblt** [comment]
Beyond the answer I've quoted, I won't be able to help you any further,
since I don't know Spacemacs.  You probably should ask on either the
Spacemacs issue tracker, or the Gitter chat.

I'd like to follow any further conversation, though, especially if it
appears that the issue comes from Eziam: Please do ping me if you create
an issue or start a conversation on the Gitter chat.  I'm leaving this
issue open for now, I'll close or fix when I get more information.

Sorry I can't be of more help, and thanks for your interest in Eziam :)
I really hope you'll be able to get it to work the way you want!

elandx writes:

**Comment by elandx** [comment]
Thank you very much i really appreciate your efforts to help me.

**Comment by duianto** [comment]
@elandx 
I'm getting the same error message when trying to load `eziam-light` or `eziam-dark` in the `.spacemacs` `dotspacemacs-themes` list.

The cause of the error, seems to be that Spacemacs checks if the themes in the `dotspacemacs-themes` list, can be found in the `emacs-built-in-themes` list, or in the `spacemacs-theme-name-to-package` list, and if it doesn't find them there, then it seems to add `-theme` to the end of the theme name, and tries to download a package with that name. But since `eziam-dark` or `eziam-light`, are themes inside the `eziam-theme` package, then they can't be found.

The other themes you tried, `tao-yin/yang`, `spacemacs-light/dark` and `solarized-light/dark`, work because they are supported by Spacemacs, since they have entries in the `spacemacs-theme-name-to-package` list.


I found 3 ways of loading the `eziam-light` or `eziam-dark` on startup.

This method loads the theme instantly when Spacemacs starts:
In the `spacemacs-theme-name-to-package` list, that's defined in: `.emacs.d/core/core-themes-support.el`, add:
```elisp
    (eziam-light                      . eziam-theme)
    (eziam-dark                       . eziam-theme)
```
and add the desired theme name, to the `dotspacemacs-themes` list in `.spacemacs`.

This method probably won't need an entry for `eziam-theme` in the `dotspacemacs-additional-packages` list. Because I'm guessing that Spacemacs automatically checks for updates and re-downloads the package if the package directory is removed. When it's listed in the `spacemacs-theme-name-to-package` list.

One issue with modifying this locally, is that if this file is changed the next time Spacemacs is updated, then the local changes will be removed. Therefore it probably is best to make a PR that adds support for 
`eziam-theme` to Spacemacs.

Here's an example how a recent PR added support for several doom themes:
core: Add support for more doom themes
https://github.com/syl20bnr/spacemacs/pull/9088/files

The other two methods will start Spacemacs with the first supported theme in the `dotspacemacs-themes` list. And then changes to the `eziam-light/dark` theme when the user-config section in `.spacemacs` is loaded.

With `eziam-theme` added to the `dotspacemacs-additional-packages` list:
Add: `(eziam-dark :location local)` to the `dotspacemacs-themes` list.

Or instead of adding an entry to the `dotspacemacs-themes` list, add one of these commands to the `dotspacemacs/user-config` section.
`(load-theme 'eziam-dark t)`
or
`(spacemacs/load-theme 'eziam-dark)`

I'm not sure what the difference between the commands are, but both seem to work.

**Comment by elandx** [comment]
@duianto 
Thank you for the clarifications. I did not suspect that there is a mechanism for "certifying" colour themes in Spacemacs, it's at least a bit strange in my opinion. So this is not a problem of Eziam but a problem of Spacemacs. I close the issue. Once again, thank you all for your help.

**Comment by thblt** [comment]
Thanks again, @duianto.  I'll submit a PR to Spacemacs to let it know about Eziam soon.
